{
 "title": "Meshtastic Packets (Net)",
 "tags": [
  "meshtastic",
  "mesh"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Packet rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(meshtastic_mesh_packets_total{via_mqtt=\"false\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets by hop limit",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hop_limit) (increase(meshtastic_mesh_packets_total[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets by source & type (broadcast)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(source, source_long_name, type) (increase(meshtastic_mesh_packets_total{to=\"4294967295\"}[$__interval]))",
     "legendFormat": "{{source_long_name}} ({{source}}) - {{type}}"
    }
   ]
  },
  {
   "title": "Packets by talkers & type (unicast)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(to, from, to_long_name, from_long_name, type) (increase(meshtastic_mesh_packets_total{to!=\"4294967295\"}[$__interval]))",
     "legendFormat": "{{from_long_name}} ({{from}}) -> {{to_long_name}} ({{to}}) - {{type}}"
    }
   ]
  },
  {
   "title": "Packets by type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(meshtastic_mesh_packets_total[$__interval])) by (type) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}