{
 "title": "Meshtastic Telemetry (Nodes)",
 "tags": [
  "meshtastic",
  "mesh"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "source",
    "query": {
     "query": "label_values(meshtastic_mesh_packets_total,source_long_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meshtastic_telemetry_device_battery_level_percent{source_long_name=~\"$source\"}",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Battery level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_battery_level_percent{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "Battery level {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Device Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meshtastic_telemetry_device_voltage_volts{source_long_name=~\"$source\"}",
     "legendFormat": "{{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_env_temperature_celsius{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "Temperature {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Barometric pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_env_barometric_pressure_pascal {source_long_name=~\"$source\"}[$__interval]) / 133.3",
     "legendFormat": "Barometric pressure {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Environment Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_env_voltage_volts{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "Environment Voltage {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Environment Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_env_current_amperes{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "Environment Current {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Channel util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_channel_utilization_percent{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "Channel util {{source_long_name}} ({{source}})"
    }
   ]
  },
  {
   "title": "Air util tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(meshtastic_telemetry_device_air_util_tx_percent{source_long_name=~\"$source\"}[$__interval])",
     "legendFormat": "Air util tx {{source_long_name}} ({{source}})"
    }
   ]
  }
 ]
}